version: '3.9'

services:
    web:
      build:
        context: .
        dockerfile: C:\Users\hasee\OneDrive\Desktop\priceoye_docker\priceoye\DockerFIle
        
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: priceoye
      ports:
        - "8000:8000"

